# Generated by Django 4.1.7 on 2023-03-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_first_name_customer_given_name_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
